
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - user-service
      - ambulance-service
      - blood-service
    networks:
      - hosta-network

  user-service:
    build: ./user-service
    env_file:
      - ./user-service/.env
    networks:
      - hosta-network

  ambulance-service:
    build: ./ambulance-service
    env_file:
      - ./ambulance-service/.env
    networks:
      - hosta-network

  blood-service:
    build: ./blood-service
    env_file:
      - ./blood-service/.env
    networks:
      - hosta-network

networks:
  hosta-network:
    driver: bridge


