version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ambulance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - hosta-network

  ambulance-service:
    build: ./ambulance-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    env_file:
      - ./ambulance-service/.env
    environment:
      - PORT=3001
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=ambulance_db
      - RABBITMQ_URL=amqps://cqneyljc:5hViP3MTU5ZIvHw8ZvVY-9O_k97o8Agw@raccoon.lmq.cloudamqp.com/cqneyljc
      - JWT_SECRET=supersecretjwtkey
      - NODE_ENV=development
    networks:
      - hosta-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - ambulance-service
    networks:
      - hosta-network

networks:
  hosta-network:
    driver: bridge
